interface/urls.py
from django.urls import path
from . import views

app_name = 'interface'

urlpatterns = [
    path('', views.survivors, name='survivors'),
    path('<int:pk>/', views.survivor_detail, name='survivor_detail'),
    
    path('<int:pk>/report_infected/', views.report_infected, name='report_infected'),
    path('<int:pk>/update_location/', views.update_location, name='update_location'),

    path('<int:pk>/make_trade/', views.make_trade, name='make_trade'),

    path('add_survivor/', views.add_survivor, name='add_survivor'),
    path('<int:pk>/delete_survivor/', views.delete_survivor, name='delete_survivor'),
    path('<int:pk>/update_location/', views.update_location, name='update_location'),

    path('resources_report/', views.resources_report, name='resources_report'),
]

zssn/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from api.views import SurvivorViewSet
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'survivors', SurvivorViewSet, basename='survivors')

urlpatterns = [
    path('', include('interface.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

interface/views.py
import requests
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
import json


def survivors(request):
    response = requests.get('https://zssn-vmb.herokuapp.com/api/survivors/')
    survivors = response.json()
    context = {'survivors': survivors}
    return render(request, 'interface/survivors.html', context)

def survivor_detail(request, pk):
    response = requests.get(f'https://zssn-vmb.herokuapp.com/api/survivors/{pk}/')
    survivor = response.json()

    response = requests.get('https://zssn-vmb.herokuapp.com/api/survivors/')
    survivors = response.json()
    
    context = {'survivor': survivor, 'survivors': survivors}
    return render(request, 'interface/survivor_detail.html', context)

def resources_report(request):
    response = requests.get('https://zssn-vmb.herokuapp.com/api/survivors/get_resources_report/')
    context = {'report': response.json()}
    print(response)
    return render(request, 'interface/resources_report.html', context)

def report_infected(request, pk):
    data = {
            'survivor_reported': request.POST.get('survivor_reported'),
            'latitude': float(request.POST.get('latitude')),
            'longitude': float(request.POST.get('longitude')),
            }
    print(data)
    response = requests.put(f'https://zssn-vmb.herokuapp.com/api/survivors/{pk}/report_infected/', json=data)
    return redirect(reverse('interface:survivor_detail', kwargs={'pk': pk}))

def update_location(request, pk):
    if request.method == 'POST':
        latitude = request.POST.get('latitude')
        longitude = request.POST.get('longitude')
        data = {'latitude': latitude, 'longitude': longitude}
        print(data)
        requests.patch(f'https://zssn-vmb.herokuapp.com/api/survivors/{pk}/', data=data)
        return redirect(reverse('interface:survivor_detail', kwargs={'pk': pk}))
    response = requests.get(f'https://zssn-vmb.herokuapp.com/api/survivors/{pk}/')
    survivor = response.json()
    return render(request, 'interface/update_location.html', {'survivor': survivor})

def add_survivor(request):
    if request.method == 'POST':
        data = {
            'name': request.POST.get('name'),
            'age': request.POST.get('age'),
            'sex': request.POST.get('sex'),
            'latitude': request.POST.get('latitude'),
            'longitude': request.POST.get('longitude'),
            'infected': request.POST.get('infected', False),
            "points": 0,
            "reports": 0,
            'water': request.POST.get('water'),
            'food': request.POST.get('food'),
            'medication': request.POST.get('medication'),
            'ammunition': request.POST.get('ammunition'),
        }
        requests.post('https://zssn-vmb.herokuapp.com/api/survivors/', data=data)
        return redirect(reverse('interface:survivors'))
    return render(request, 'interface/add_survivor.html')

def delete_survivor(request, pk):
    response = requests.delete(f'https://zssn-vmb.herokuapp.com/api/survivors/{pk}/')
    return redirect(reverse('interface:survivors'))

def make_trade(request, pk):
    if request.method == 'POST':
        data = {
            "survivor1": pk,
            "survivor2": request.POST['survivor2'],
            "survivor1_items": request.POST.getlist('survivor1_items'),
            "survivor2_items": request.POST.getlist('survivor2_items')
        }
        print(data)
        requests.post(f"https://zssn-vmb.herokuapp.com/api/survivors/make_trade/", data=data)
        return redirect(reverse('interface:survivor_detail', kwargs={'pk': pk}))

    response = requests.get(f'https://zssn-vmb.herokuapp.com/api/survivors/{pk}/')
    survivor1 = response.json()

    response = requests.get(f'https://zssn-vmb.herokuapp.com/api/survivors/{request.GET["survivor2"]}/')
    survivor2 = response.json()
    
    context = {'survivor1': survivor1, 'survivor2': survivor2}
    return render(request, 'interface/make_trade.html', context)

interface/templates/interface/add_survivor.html
{% extends 'interface/base.html' %}

{% block content %}
<h1>Adicionar Sobrevivente</h1>

<form action="{% url 'interface:add_survivor' %}" method="POST">
    {% csrf_token %}
    <label for="name">Nome:</label>
    <input type="text" id="name" name="name">
    <br>
    <label for="age">Idade:</label>
    <input type="number" id="age" name="age">
    <br>
    <label for="sex">Sexo:</label>
    <select name="sex" id="sex">
        <option value="F">Feminino</option>
        <option value="M">Masculino</option>
    </select>
    <br><br>
    <label>Localização: </label><br>
    latitude: <input type="text" id="latitude" name="latitude"><br>
    longitude: <input type="text" id="longitude" name="longitude"><br>
    <br><br>
    infected: <input type="checkbox" name="infected" id="infected" value="True" default="False">
    <br><br>
    <label>Inventário:</label><br>
    water: <input type="text" id="water" name="water"><br>
    food: <input type="text" id="food" name="food"><br>
    medication: <input type="text" id="medication" name="medication"><br>
    ammunition: <input type="text" id="ammunition" name="ammunition"><br>
    <br>
    <input type="submit" value="Adicionar">
</form>

<a href="{% url 'interface:survivors' %}">Voltar</a>
{% endblock %}

interface/templates/interface/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>ZSSN</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav>
        <a href="{% url 'interface:survivors' %}">Survivors</a>
        <a href="{% url 'interface:resources_report' %}">Resources Report</a>
    </nav>
    {% block content %}{% endblock %}
</body>

</html>

interface/templates/interface/make_trade.html
{% extends 'interface/base.html' %}

{% block content %}

<div class="trade-container">
  <form method="post" action="{% url 'interface:make_trade' survivor1.id %}">
    {% csrf_token %}
    <div class="survivor-container">
      <h2>Survivor 1</h2>
      <label>Name: {{ survivor1.name }}</label>
      <label>Points: {{ survivor1.points }}</label>
      <div class="resources">
        <label>Water: {{ survivor1.water }}</label>
        <label>Food: {{ survivor1.food }}</label>
        <label>Medication: {{ survivor1.medication }}</label>
        <label>Ammunition: {{ survivor1.ammunition }}</label>
      </div>
    </div>
    <div class="survivor-container">
      <h2>Survivor 2</h2>
      <label>Name: {{ survivor2.name }}</label>
      <label>Points: {{ survivor2.points }}</label>
      <div class="resources">
        <label>Water: {{ survivor2.water }}</label>
        <label>Food: {{ survivor2.food }}</label>
        <label>Medication: {{ survivor2.medication }}</label>
        <label>Ammunition: {{ survivor2.ammunition }}</label>
      </div>
    </div>
    <div class="trade-items">
      <h2>Items to trade</h2>
      <div class="resources">
        <label>Water: <input type="number" name="survivor1_items" value="0"></label>
        <label>Food: <input type="number" name="survivor1_items" value="0"></label>
        <label>Medication: <input type="number" name="survivor1_items" value="0"></label>
        <label>Ammunition: <input type="number" name="survivor1_items" value="0"></label>
      </div>
      <h2>Items to receive</h2>
      <div class="resources">
        <label>Water: <input type="number" name="survivor2_items" value="0"></label>
        <label>Food: <input type="number" name="survivor2_items" value="0"></label>
        <label>Medication: <input type="number" name="survivor2_items" value="0"></label>
        <label>Ammunition: <input type="number" name="survivor2_items" value="0"></label>
      </div>
    </div>
    <input type="hidden" name="survivor2" value="{{ survivor2.id }}">
    <input type="submit" value="Make trade">
  </form>

</div>
{% endblock %}

interface/templates/interface/resources_report.html
{% extends 'interface/base.html' %}

{% block content %}

<h1>Survivors Resources Report</h1>
<table>
  <thead>
    <tr>
      <th>Resource</th>
      <th>Total</th>
      <th>Average</th>
    </tr>
  </thead>
  <tbody>
    {% for resource, data in report.resources.items %}
    <tr>
      <td>{{ resource }}</td>
      <td>{{ data.total }}</td>
      <td>{{ data.average }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<p>Population:</p>
<p>Total: {{ report.population.total }}</p>
<p class="infected">Infected: {{ report.population.infected }}</p>
<p class="non-infected">Non-Infected: {{ report.population.non_infected }}</p>
<p class="percent">Percent infected: {{ report.population.percent_infected }}</p>
{% endblock %}

interface/templates/interface/survivor_detail.html
{% extends 'interface/base.html' %}

{% block content %}
  <h1>Survivor Detail</h1>
  <ul>
    <li>Name: {{ survivor.name }}</li>
    <li>Age: {{ survivor.age }}</li>
    <li>Sex: {{ survivor.sex }}</li>
    <li>Latitude: {{ survivor.latitude }}</li>
    <li>Longitude: {{ survivor.longitude }}</li>
    <li>Infected: {{ survivor.infected }}</li>
    <li>Points: {{ survivor.points }}</li>
    <li>Reports: {{ survivor.reports }}</li>
    <li>Inventory:
      <ul>
        <li>Water: {{ survivor.water }}</li>
        <li>Food: {{ survivor.food }}</li>
        <li>Medication: {{ survivor.medication }}</li>
        <li>Ammunition: {{ survivor.ammunition }}</li>
    </ul>
  </li>
</ul>
<h2>Actions</h2>
<ul>
  <li>
    <a href="{% url 'interface:update_location' survivor.id %}">Update Location</a>
  </li>
  <li>
    <form action="{% url 'interface:make_trade' survivor.id %}" method="get">
      {% csrf_token %}
      SURVIVOR: <select name="survivor2" id="survivor2">
      {% for survivor in survivors %}
        <option value="{{ survivor.id }}">{{ survivor.name }} | Reports: {{ survivor.reports }}</option>
      {% endfor %}
      </select>
      <input type="submit" value="Go Make Trade">
    </form>
  </li>
  <li>
    <form action="{% url 'interface:report_infected' survivor.id %}" method="post">
      {% csrf_token %}
      SURVIVOR: <select name="survivor_reported" id="survivor_reported">
      {% for survivor in survivors %}
        <option value="{{ survivor.id }}">{{ survivor.name }} | Reports: {{ survivor.reports }}</option>
      {% endfor %}
      </select><br><br>
      <label>Localização: </label><br>
      latitude: <input type="number" id="latitude" name="latitude"><br>
      longitude: <input type="number" id="longitude" name="longitude"><br>
      <br><br>
      <input type="submit" value="Report Infected">
    </form>
  </li>
</ul>
{% endblock %}

interface/templates/interface/survivors.html
{% extends 'interface/base.html' %}

{% block content %}
<h1>Survivors</h1>
<a href="{% url 'interface:add_survivor' %}">add_survivor</a>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Sex</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Infected</th>
            <th>Points</th>
            <th>Reports</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for survivor in survivors %}
        <tr>
            <td>{{ survivor.name }}</td>
            <td>{{ survivor.age }}</td>
            <td>{{ survivor.sex }}</td>
            <td>{{ survivor.latitude }}</td>
            <td>{{ survivor.longitude }}</td>
            <td>{{ survivor.infected }}</td>
            <td>{{ survivor.points }}</td>
            <td>{{ survivor.reports }}</td>
            <td>
                <a href="{% url 'interface:survivor_detail' survivor.id %}">Detail</a>
                <a href="{% url 'interface:delete_survivor' survivor.id %}">delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock %}

interface/templates/interface/update_location.html
{% extends 'interface/base.html' %}

{% block content %}
<h1>Update Location</h1>
<form action="{% url 'interface:update_location' survivor.id %}" method="POST">
    {% csrf_token %}
    <label for="latitude">Latitude:</label>
    <input type="text" id="latitude" name="latitude" value="{{ survivor.latitude }}">
    <label for="longitude">Longitude:</label>
    <input type="text" id="longitude" name="longitude" value="{{ survivor.longitude }}">
    <input type="submit" value="Update">
</form>
{% endblock %}